#!/bin/bash

function send_log() {
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIFICATIONS MULTI LOGIN SSH⚠️</b>
<code>────────────────────</code>
<code>Username          : </code><code>$user</code>
<code>Limit IP            : </code><code>${iplimit}</code>
<code>User Login         : </code><code>${cekcek}</code>
<code>Akun Locked       : </code><code>15 Menit</code>
<code>────────────────────</code>
"
    curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
function send_log_owner_bot() {
    CHATIDX="7200407209:AAH0DHDuM_KoxQA_yMAINBjHnky3p5TodgQ"
    KEYX="1626302370"
    TIME="10"
    URLX="https://api.telegram.org/bot$KEYX/sendMessage"
    TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIFICATIONS MULTI LOGIN SSH⚠️</b>
<code>────────────────────</code>
<code>Username          : </code><code>$user</code>
<code>Limit IP            : </code><code>${iplimit}</code>
<code>User Login         : </code><code>${cekcek}</code>
<code>Akun Locked       : </code><code>15 Menit</code>
<code>────────────────────</code>
"
    curl -s --max-time $TIME -d "chat_id=$CHATIDX&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URLX >/dev/null
}

clear

mulog=$(cek-ssh)
date=$(date)
data=( `ls /etc/kyt/limit/ssh/ip`)

for user in "${data[@]}"
do
    iplimit=$(cat /etc/kyt/limit/ssh/ip/$user)
    cekcek=$(echo -e "$mulog" | grep $user | wc -l)

    if [[ $cekcek -gt $iplimit ]]; then
        nais=3
        passwd -l "$user" > /dev/null
        send_log
        send_log_owner_bot

        # Jadwalkan untuk membuka kembali akun setelah 15 menit
        echo "passwd -u $user" | at now + 15 minutes > /dev/null
        systemctl restart ws && systemctl restart dropbear
    else
        echo > /dev/null
    fi

    sleep 0.1
done

echo > /dev/null
